"""Exercise admin Anlas/modules/upscale with the isolated preview server, without real spending."""
import io, json, re
from pathlib import Path
from PIL import Image
from playwright.sync_api import sync_playwright, expect

expect.set_options(timeout=15000)
ROOT = Path(__file__).resolve().parents[1]

def login(page, username):
    page.get_by_label('账号', exact=True).fill(username)
    page.get_by_label('密码', exact=True).fill('preview-password')
    page.get_by_role('button', name='进入创作工作台').click()

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, args=['--no-sandbox'])
    context = browser.new_context(viewport={'width': 1440, 'height': 1000})
    page = context.new_page()
    errors, submitted = [], []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.on('request', lambda req: submitted.append(req.post_data_json) if req.url.endswith('/api/generate') else None)
    page.goto('http://127.0.0.1:6007')
    login(page, 'preview-admin')
    expect(page.locator('.anlas-balance')).to_contain_text('1050')
    for item in context.request.get('http://127.0.0.1:6007/api/admin/prompts').json()['prompts']:
        if item['name'] == 'UI artist': context.request.delete('http://127.0.0.1:6007/api/admin/prompts/' + item['id'])
    expect(page.locator('.anlas-balance')).to_contain_text('1050')
    quality = page.locator('.prompt-module').filter(has=page.locator('summary').filter(has_text=re.compile('^质量风格')))
    assert not quality.evaluate('(e) => e.open')
    page.get_by_role('button', name='管理中心', exact=True).click()
    page.get_by_role('button', name='提示词模块', exact=True).click()
    page.get_by_role('button', name='新增提示词', exact=True).click()
    page.get_by_label('显示名称', exact=True).fill('UI artist')
    page.get_by_label('提示词', exact=True).fill('artist:ui_example')
    page.get_by_role('button', name='Danbooru', exact=True).click()
    expect(page.get_by_label('跳转 URL', exact=True)).to_have_value('https://danbooru.donmai.us/posts?tags=ui_example')
    png = io.BytesIO(); Image.new('RGB', (80,60), '#aabbcc').save(png, format='PNG')
    page.get_by_label('演示预览', exact=True).set_input_files({'name': 'preview.png', 'mimeType': 'image/png', 'buffer': png.getvalue()})
    page.get_by_role('button', name='保存提示词', exact=True).click()
    expect(page.get_by_role('status')).to_have_text('提示词已保存。')
    page.locator('.module-manager-item').filter(has_text='UI artist').get_by_role('button').click()
    expect(page.get_by_alt_text('当前演示预览', exact=True)).to_be_visible()
    page.wait_for_function('document.querySelector(".manager-preview")?.naturalWidth > 0')
    page.get_by_label('跳转 URL', exact=True).fill('https://danbooru.donmai.us/posts?tags=alternate')
    page.get_by_role('button', name='保存提示词', exact=True).click()
    expect(page.get_by_role('status')).to_have_text('提示词已保存。')
    page.get_by_role('button', name='返回工作台', exact=True).click()
    page.locator('.module-library > summary').filter(has_text='添加画师串').click()
    page.get_by_role('button', name='UI artist', exact=True).click()
    expect(page.get_by_label('artist:ui_example 权重', exact=True)).to_have_text('0.8')
    page.get_by_role('button', name='artist:ui_example 权重加 0.1', exact=True).click()
    expect(page.get_by_label('artist:ui_example 权重', exact=True)).to_have_text('0.9')
    page.get_by_role('button', name='artist:ui_example 权重减 0.1', exact=True).click()
    expect(page.get_by_label('artist:ui_example 权重', exact=True)).to_have_text('0.8')
    expect(page.get_by_role('link', name='Danbooru UI artist', exact=True)).to_have_attribute('href', 'https://danbooru.donmai.us/posts?tags=alternate')
    page.get_by_role('button', name='预览 UI artist', exact=True).click()
    expect(page.get_by_role('dialog', name='提示词预览')).to_be_visible()
    page.get_by_role('button', name='关闭提示词预览').click()
    page.get_by_label('场景提示词', exact=True).fill('forest')
    page.get_by_role('button', name='大竖图', exact=False).click()
    expect(page.get_by_label('允许使用 Anlas', exact=True)).to_be_checked()
    expect(page.locator('.anlas-settings')).to_contain_text('39 Anlas')
    page.get_by_role('button', name='生成图像', exact=True).click()
    expect(page.get_by_role('button', name='继续重绘', exact=True)).to_be_enabled()
    assert submitted[-1]['resolution'] == 'largePortrait' and submitted[-1]['useAnlas']
    assert submitted[-1]['promptModules'][0]['weight'] == 0.8 or any(m['weight'] == .8 for m in submitted[-1]['promptModules'])
    expect(page.locator('.result-meta')).to_contain_text('1024 × 1536')
    page.get_by_label('允许使用 Anlas', exact=True).uncheck()
    page.get_by_role('button', name='生成图像', exact=True).click()
    expect(page.get_by_role('button', name='原生放大 2× · 1 Anlas', exact=True)).to_be_enabled()
    assert submitted[-1]['resolution'] == 'portrait' and not submitted[-1]['useAnlas']
    page.get_by_role('button', name='原生放大 2× · 1 Anlas', exact=True).click()
    expect(page.locator('.result-meta')).to_contain_text('1664 × 2432')
    expect(page.get_by_role('button', name='继续重绘', exact=True)).to_be_enabled()
    page.get_by_role('button', name='复制提示词', exact=True).click()
    expect(page.get_by_label('artist:ui_example 权重', exact=True)).to_have_text('0.8')
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('button', name='提示词', exact=True).click()
    expect(page.get_by_label('artist:ui_example 权重', exact=True)).to_be_visible()
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
    assert page.locator('.prompt-scroll').evaluate('(e) => e.scrollWidth <= e.clientWidth + 1')
    page.wait_for_function('document.querySelector(".module-preview img")?.naturalWidth > 0')
    page.screenshot(path=str(ROOT/'artifacts/novelai-prompt-modules-mobile.png'))
    page.get_by_role('button', name='关闭提示词面板', exact=True).click()
    page.get_by_role('button', name='设置', exact=True).click()
    expect(page.locator('.anlas-balance')).to_contain_text('1050')
    assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
    page.screenshot(path=str(ROOT/'artifacts/novelai-anlas-mobile.png'))
    page.get_by_role('button', name='关闭设置面板', exact=True).click()
    page.get_by_role('button', name='管理中心', exact=True).click()
    page.get_by_role('button', name='提示词模块', exact=True).click()
    page.locator('.module-manager-item').filter(has_text='UI artist').get_by_role('button').click()
    page.get_by_role('button', name='删除', exact=True).click()
    page.get_by_role('button', name='确认删除', exact=True).click()
    expect(page.get_by_role('status')).to_have_text('提示词已删除。')
    expect(page.locator('.module-manager-item').filter(has_text='UI artist')).to_have_count(0)
    user_context = browser.new_context(viewport={'width':390,'height':844})
    user = user_context.new_page(); user.goto('http://127.0.0.1:6007'); login(user,'preview-user')
    user.get_by_role('button', name='设置', exact=True).click()
    expect(user.get_by_label('允许使用 Anlas', exact=True)).to_have_count(0)
    expect(user.get_by_role('button', name='大竖图')).to_have_count(0)
    response = user_context.request.post('http://127.0.0.1:6007/api/admin/upscale', data={'image':'fixture'})
    assert response.status == 403
    assert not errors, errors
    browser.close()
    print('Admin modules, preview upload, weights, paid presets, upscale, metadata reuse, permissions and mobile layout passed.')
